name       : budgie-restart-applet
version    : 1.0
release    : 1
source     :
    - https://github.com/gkr09/budgie-restart/archive/v1.0.tar.gz : 68fcaf923de7f2aa812f988fabf6a290de39dde84c43248122b12b616bc99a78
license    : GPL-3.0-or-later
component  : desktop.budgie
summary    : Budgie Restart Applet
description: |
    Restart the budgie panel, WM or both from your Budgie desktop.
rundeps  :
    - python3-gobject
install    : |
    install -D -m00644 icons/budgie-restart.svg $installdir/usr/share/icons/hicolor/scalable/apps/budgie-restart.svg
    install -D -m00644 BudgieRestart/BudgieRestart.plugin $installdir/%libdir%/budgie-desktop/plugins/org.budgie-desktop.applet.budgierestart/BudgieRestart.plugin
    install -m00755 BudgieRestart/budgierestart.py $installdir/%libdir%/budgie-desktop/plugins/org.budgie-desktop.applet.budgierestart/budgierestart.py

    %python3_compile
